---
deployment: "{{ lookup('env', 'DEPLOYMENT') }}"

# Openshift project/namespace name
project: dist2src-update

# Openshift cluster url
host: https://api.ocp4.prod.psi.redhat.com:6443

# Openshift API key, please define in vars/*.yml
api_key: ""

# Set to 'no' when deploying to local cluster
validate_certs: yes

# Set to 'true' when deploying to local cluster
push_dev_images: false

image_worker: quay.io/packit/dist2src:{{ deployment }}

image_centosmsg: quay.io/packit/packit-service-centosmsg:prod

# How many workers
worker_replicas: 2

# sent by centosmsg pod and processed by worker(s)
celery_task_name: task.dist2src.process_message

container_engine: "{{ lookup('pipe', 'command -v podman 2> /dev/null || echo docker') }}"

# Whether to periodically import image(s) from registry to image stream(s)
auto_import_images: true

# Pushgateway URL used for monitoring.
# Leave empty to disable pushing monitoring information.
pushgateway_address: http://pushgateway

# Path within the worker container where the work is done
workdir: /workdir

# URL for the forge where the dist-git and source-git repos are stored.
# For now, the forge is expected to be running Pagure.
# The corresponding tokens are expected to be stored in the secrets dir.
dist_git_host: git.centos.org
src_git_host: gitlab.com

# Dist-git branches which should be monitored for changes
branches_watched:
  - c8s
  # in the first iteration, we only want to take care of c8s
  # - c8
  # - c8s-stream-rhel

# Namespace where the dist-git repositories are stored in the forge
dist_git_namespace: rpms

# Namespace where the source-git repositories are stored in the forge
src_git_namespace: redhat/centos-stream/src

mqtt_host: mqtt.git.centos.org
mqtt_topics: git.centos.org/#

# Seconds until Celery tasks created by the scheduled update job expire
update_task_expires: 82800
