# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Push dev images to local registry
  block:
    - set_fact: tls_verify_false="{{ '--tls-verify=false' if 'podman' in container_engine else '' }}"
    - shell: "{{ container_engine }} login -u developer -p $(oc whoami -t) 172.30.1.1:5000 {{ tls_verify_false }}"
    - command: "{{ container_engine }} inspect {{ image_worker }}"
    - command: "{{ container_engine }} tag {{ image_worker }} 172.30.1.1:5000/myproject/worker:dev"
    # this is default minishift's docker-registry, make sure it's running via
    #   oc get svc/docker-registry -n default
    - command: "{{ container_engine }} push 172.30.1.1:5000/myproject/worker:dev {{ tls_verify_false }}"
  #    - command: "{{ container_engine }} inspect {{ image_centosmsg }}"
  #    - command: "{{ container_engine }} tag {{ image_centosmsg }} 172.30.1.1:5000/myproject/dist2src-centosmsg"
  #    - command: "{{ container_engine }} push 172.30.1.1:5000/myproject/dist2src-centosmsg {{ tls_verify_false }}"
  tags:
    - worker
#    - centosmsg
